In [2]:
####Can we use KNN to predict whether we should play or not?

#Let's import needed libraries:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from matplotlib.ticker import NullFormatter
from sklearn import preprocessing
import itertools
%matplotlib inline

In [3]:
df = pd.read_csv("C:\\Users\\fabri\\OneDrive\\Documents\\DasText\\csvFiles\\weatherData.csv")
df

Outlook  Temperature  Humidity  Windy Play?
0      sunny           85        85  False    no
1      sunny           80        90   True    no
2   overcast           83        78  False   yes
3       rain           70        96  False   yes
4       rain           68        80  False   yes
5       rain           65        70   True    no
6   overcast           64        65   True   yes
7      sunny           72        95  False    no
8      sunny           69        70  False   yes
9       rain           75        80  False   yes
10     sunny           75        70   True   yes
11  overcast           72        90   True   yes
12  overcast           81        75  False   yes
13      rain           71        80   True    no

In [4]:
df.dtypes

Outlook        object
Temperature     int64
Humidity        int64
Windy            bool
Play?          object
dtype: object

In [5]:
####HOW TO MAP VALUES TO CATEGORICAL VALUES

#Start by making df of just non-numericals you want to map to numerical values
obj_df = df.select_dtypes(include=['object','bool']).copy()
obj_df.head()

Outlook  Windy Play?
0     sunny  False    no
1     sunny   True    no
2  overcast  False   yes
3      rain  False   yes
4      rain  False   yes

In [6]:
#let's look at the unique values that we are going to map
obj_df['Outlook'].value_counts()

sunny       5
rain        5
overcast    4
Name: Outlook, dtype: int64

In [7]:
#now we map them
cleanup_nums = {"Outlook":     {"sunny": 2, "overcast": 1, "rain": 0},
                "Windy": {True: 1, False: 0},
                "Play?": {"no": 0, "yes": 1}}

In [8]:
#use replace method!
df.replace(cleanup_nums, inplace=True)
df.head()

Outlook  Temperature  Humidity  Windy  Play?
0        2           85        85      0      0
1        2           80        90      1      0
2        1           83        78      0      1
3        0           70        96      0      1
4        0           68        80      0      1

In [9]:
#nice! Let's check the value types again now
df.dtypes

Outlook        int64
Temperature    int64
Humidity       int64
Windy          int64
Play?          int64
dtype: object

In [18]:
#***To use scikit-learn library, we have to convert the Pandas data frame to a Numpy array
X = df[['Outlook','Temperature','Humidity','Windy']].values
print("X data: \n" + str(X[0:5]))
y = df['Play?'].values
print("\nY data: \n"+str(y[0:5]))

X data: 
[[ 2 85 85  0]
 [ 2 80 90  1]
 [ 1 83 78  0]
 [ 0 70 96  0]
 [ 0 68 80  0]]

Y data: 
[0 0 1 1 1]
